com.example.ridempang.MainActivity Class Reference
Public Member Functions
void onCreate (Bundle savedInstanceState)
boolean onCreateOptionsMenu (Menu menu)
Additional Inherited Members
Detailed Description
Definition at line 10 of file MainActivity.java.
Member Function Documentation
void com.example.ridempang.MainActivity.onCreate (Bundle savedInstanceState)
Definition at line 13 of file MainActivity.java.
References Technology.Base.TechnologyActivity.ApplyCurrentLayout(), Technology.Base.TechnologyActivity.InitTechnologyActivity(), and Technology.Base.TechnologyActivity.SetGameView().
boolean com.example.ridempang.MainActivity.onCreateOptionsMenu (Menu menu)
Definition at line 25 of file MainActivity.java.
The documentation for this class was generated from the following file:
src/com/example/ridempang/MainActivity.java