KeyboardPang.GamePlayer Class Reference
이 객체는 생성되면 자동으로 월드에 등록한다. 이 클래스를 상속받으면 월드에 두번 추가가 될수 있기때문에 상속받지않는다.
Public Member Functions
GamePlayer (String id, float x, float y)
void onActionDown (int x, int y)
void onActionMove (int x, int y)
void onActionUp (int x, int y)
Detailed Description
이 객체는 생성되면 자동으로 월드에 등록한다. 이 클래스를 상속받으면 월드에 두번 추가가 될수 있기때문에 상속받지않는다.
Definition at line 15 of file GamePlayer.java.
Constructor & Destructor Documentation
KeyboardPang.GamePlayer.GamePlayer (String id, float x, float y)
Definition at line 16 of file GamePlayer.java.
References Technology.Game.GameWorld.Add(), and Technology.Game.GameWorld.getInstance().
Member Function Documentation
void KeyboardPang.GamePlayer.onActionDown (int x, int y)
Definition at line 22 of file GamePlayer.java.
References Technology.Util.GameSound.getInstance(), and Technology.Util.GameSound.Play().
void KeyboardPang.GamePlayer.onActionMove (int x, int y)
Definition at line 36 of file GamePlayer.java.
void KeyboardPang.GamePlayer.onActionUp (int x, int y)
Definition at line 41 of file GamePlayer.java.
The documentation for this class was generated from the following file:
src/KeyboardPang/GamePlayer.java